### ISSUE TITLE
Sensor will not be spawned, Inbound TCP/IP connection failed, necessary topics are not subscribed

### ISSUE THREAD

**Issue by Jasonzhang11111** [carla-simulator/carla-autoware#107]
Hi I have been installing dockers for both Carla 0.9.10.1 and carla-autoware in this repo, and running them in parallel. 

Previously I could see the map and access the topics for the ego using rviz after `roslaunch carla_autoware_agent carla_autoware_agent.launch town:=Town01`, problem I encountered earlier is it "Failed transform from base_link to ego_vehicle/lidar/lidar1", and the ego vehicle nevers moved.

However I build the carla-autoware image again yesterday, and I got 'Sensor will not be spawned', 'Inbound TXP/IP connection failed' and 'necessary topic are not subscribed' error, in rviz there is no map showing and many of the topics for the ego are missing, please see screenshots below. Could anyone please guide me on how to properly build the carla-autoware image, and how to run carla 0.9.10.1 docker with this carla-autoware? thanks

![1](https://user-images.githubusercontent.com/53444361/97282076-256af800-1836-11eb-905b-47e08a6f6d11.png)
![2](https://user-images.githubusercontent.com/53444361/97282082-27cd5200-1836-11eb-9302-33fabb000597.png)
![4](https://user-images.githubusercontent.com/53444361/97282093-2a2fac00-1836-11eb-8c71-9f34551d5d08.png)

**Comment by Jasonzhang11111** [comment]
I solved this one! I didn't install git lfs. After installing it, repeat the whole process and everything works

**Comment by oth54477** [comment]
Hi. 
I had the same error as you.
Can you tell me in detail how you solved it?

**Comment by mattdst1** [comment]
Hi any updates on this one? I'm getting the same issue and not sure how to move forwards

**Comment by jasonxzzhang** [comment]
hi @oth54477 @mattdst1, I can't remember exactly what I did that got it work as I tried many different ways on different PCs. I think if you haven't tried maybe worth re-cloning both Carla and Autoware, and make sure that git lfs is installed

**Comment by mattdst1** [comment]
Brilliant thank you for the information. I’ll give a re clone a go.

Kind regards
Matt
