### ISSUE TITLE
How to set Waypoints in Rviz using carla-autoware

### ISSUE THREAD

**Issue by Amina88** [carla-simulator/carla-autoware#111]
I have installed newest version of carla and carla autoware docker and now i want to set carla autoware waypoint setting in the rviz

Any ideas how to set that.

**Comment by joel-mb** [comment]
Hi @Amina88,
Do you mean setting a target location for the global planner? You can set the target location using the `2D Nav Goal` button in `rviz`.

**Comment by Amina88** [comment]
I have hit the 2d nav goal and set the target location and it drives itself but do not see the waypoints along the trajectory and the different coordinates
