### ISSUE TITLE
Installation error after docker installation

### ISSUE THREAD

**Issue by kanakab** [carla-simulator/carla-autoware#125]
I have previously installed Autoware everything was working was able to launch runtime manager and play the demo file. To build the autoware bridge, I followed the steps by installing docker and nvidia docker. After this installation I am not able to use the commands ./run.sh or ./build.sh

When I run the command ./run.sh. I am getting the follwing output:

Unable to find image 'carla-autoware:latest' locally
docker: Error response from daemon: pull access denied for carla-autoware, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

When I run the command ./build.sh. I am getting the follwing output:
Summary: 154 packages finished [45.8s]
Removing intermediate container daf57ac4f1c2
 ---> fc0b1e1ff73e
Step 7/20 : RUN mkdir ./PythonAPI
 ---> Running in 701e631cee77
Removing intermediate container 701e631cee77
 ---> 587e67195d95
Step 8/20 : ADD --chown=autoware https://carla-releases.s3.eu-west-3.amazonaws.com/Backup/carla-0.9.10-py2.7-linux-x86_64.egg ./PythonAPI
Downloading [==================================================>]  25.67MB/25.67MB
 ---> 7ed468c08c42
Step 9/20 : RUN echo "export PYTHON2_EGG=$(ls /home/autoware/PythonAPI | grep py2.)" >> .bashrc     && echo "export PYTHONPATH=\$PYTHONPATH:~/PythonAPI/\$PYTHON2_EGG" >> .bashrc
 ---> Running in 0f58e02eca00
Removing intermediate container 0f58e02eca00
 ---> e67fb32efae7
Step 10/20 : RUN sudo rm -f /etc/apt/sources.list.d/ros1-latest.list
 ---> Running in c65a14ee3b35
Removing intermediate container c65a14ee3b35
 ---> 8393810c6247
Step 11/20 : RUN sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 4B63CF8FDE49746E98FA01DDAD19BAB3CBF125EA
 ---> Running in b2c6f3e9c4e8
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.GEFTbANDpd/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 4B63CF8FDE49746E98FA01DDAD19BAB3CBF125EA
gpg: key AD19BAB3CBF125EA: public key "ROS Snapshot builder <rosbuild@ros.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Removing intermediate container b2c6f3e9c4e8
 ---> 3a8c873d5795
Step 12/20 : RUN sudo sh -c 'echo "deb http://snapshots.ros.org/melodic/2020-08-07/ubuntu $(lsb_release -sc) main" >> /etc/apt/sources.list.d/ros-snapshots.list'
 ---> Running in 791ad4091a0f
Removing intermediate container 791ad4091a0f
 ---> bfd56a693aae
Step 13/20 : RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends         python-pip         python-wheel         ros-melodic-ackermann-msgs         ros-melodic-derived-object-msgs     && sudo rm -rf /var/lib/apt/lists/*
 ---> Running in 94248f119fbc
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [348 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1402 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2045 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [24.5 kB]
Get:7 http://snapshots.ros.org/melodic/2020-08-07/ubuntu bionic InRelease [13.8 kB]
Ign:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:11 http://snapshots.ros.org/melodic/2020-08-07/ubuntu bionic/main amd64 Packages [877 kB]
Ign:12 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:13 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [697 B]
Get:14 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release [564 B]
Get:15 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:16 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release.gpg [833 B]
Get:17 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Ign:21 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages
Get:22 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Packages [73.8 kB]
Get:21 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [603 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [378 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [31.4 kB]
Get:25 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2172 kB]
Get:26 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2476 kB]
Get:27 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]
Get:28 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]
Fetched 23.8 MB in 3s (7758 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  python-pip-whl python3-pip ros-melodic-radar-msgs
Recommended packages:
  python-all-dev python-keyring python-keyrings.alt python-xdg python3-wheel
The following NEW packages will be installed:
  python-pip python-wheel ros-melodic-ackermann-msgs
  ros-melodic-derived-object-msgs ros-melodic-radar-msgs
The following packages will be upgraded:
  python-pip-whl python3-pip
2 upgraded, 5 newly installed, 0 to remove and 405 not upgraded.
Need to get 2058 kB of archives.
After this operation, 2320 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python3-pip all 9.0.1-2.3~ubuntu1.18.04.4 [114 kB]
Get:2 http://snapshots.ros.org/melodic/2020-08-07/ubuntu bionic/main amd64 ros-melodic-radar-msgs amd64 3.0.1-1bionic.20200801.121516 [35.7 kB]
Get:3 http://snapshots.ros.org/melodic/2020-08-07/ubuntu bionic/main amd64 ros-melodic-derived-object-msgs amd64 3.0.1-1bionic.20200801.123834 [50.6 kB]
Get:4 http://snapshots.ros.org/melodic/2020-08-07/ubuntu bionic/main amd64 ros-melodic-ackermann-msgs amd64 1.0.1-0bionic.20200801.123243 [17.4 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python-pip-whl all 9.0.1-2.3~ubuntu1.18.04.4 [1653 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 python-pip all 9.0.1-2.3~ubuntu1.18.04.4 [151 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/universe amd64 python-wheel all 0.30.0-0.2 [36.4 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 2058 kB in 0s (6348 kB/s)
(Reading database ... 127175 files and directories currently installed.)
Preparing to unpack .../0-python3-pip_9.0.1-2.3~ubuntu1.18.04.4_all.deb ...
Unpacking python3-pip (9.0.1-2.3~ubuntu1.18.04.4) over (9.0.1-2.3~ubuntu1.18.04.1) ...
Preparing to unpack .../1-python-pip-whl_9.0.1-2.3~ubuntu1.18.04.4_all.deb ...
Unpacking python-pip-whl (9.0.1-2.3~ubuntu1.18.04.4) over (9.0.1-2.3~ubuntu1.18.04.1) ...
Selecting previously unselected package python-pip.
Preparing to unpack .../2-python-pip_9.0.1-2.3~ubuntu1.18.04.4_all.deb ...
Unpacking python-pip (9.0.1-2.3~ubuntu1.18.04.4) ...
Selecting previously unselected package python-wheel.
Preparing to unpack .../3-python-wheel_0.30.0-0.2_all.deb ...
Unpacking python-wheel (0.30.0-0.2) ...
Selecting previously unselected package ros-melodic-radar-msgs.
Preparing to unpack .../4-ros-melodic-radar-msgs_3.0.1-1bionic.20200801.121516_amd64.deb ...
Unpacking ros-melodic-radar-msgs (3.0.1-1bionic.20200801.121516) ...
Selecting previously unselected package ros-melodic-derived-object-msgs.
Preparing to unpack .../5-ros-melodic-derived-object-msgs_3.0.1-1bionic.20200801.123834_amd64.deb ...
Unpacking ros-melodic-derived-object-msgs (3.0.1-1bionic.20200801.123834) ...
Selecting previously unselected package ros-melodic-ackermann-msgs.
Preparing to unpack .../6-ros-melodic-ackermann-msgs_1.0.1-0bionic.20200801.123243_amd64.deb ...
Unpacking ros-melodic-ackermann-msgs (1.0.1-0bionic.20200801.123243) ...
Setting up ros-melodic-radar-msgs (3.0.1-1bionic.20200801.121516) ...
Setting up python-pip-whl (9.0.1-2.3~ubuntu1.18.04.4) ...
Setting up ros-melodic-derived-object-msgs (3.0.1-1bionic.20200801.123834) ...
Setting up ros-melodic-ackermann-msgs (1.0.1-0bionic.20200801.123243) ...
Setting up python-wheel (0.30.0-0.2) ...
Setting up python3-pip (9.0.1-2.3~ubuntu1.18.04.4) ...
Setting up python-pip (9.0.1-2.3~ubuntu1.18.04.4) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Removing intermediate container 94248f119fbc
 ---> 3eb460bc7df6
Step 14/20 : RUN pip install simple-pid pygame networkx==2.2
 ---> Running in 34331bd3ed4f
Collecting simple-pid
  Downloading https://files.pythonhosted.org/packages/f0/23/fa4e51987a031580f3af54a75eae60aacce593e23669075ae65664511244/simple_pid-1.0.0-py2.py3-none-any.whl
Collecting pygame
  Downloading https://files.pythonhosted.org/packages/d2/11/4212b97ea025aca55e2284e9c7d8cb87cfaddb4e89f5eb613c81017246c1/pygame-2.0.1-cp27-cp27mu-manylinux1_x86_64.whl (11.7MB)
Collecting networkx==2.2
  Downloading https://files.pythonhosted.org/packages/f3/f4/7e20ef40b118478191cec0b58c3192f822cace858c19505c7670961b76b2/networkx-2.2.zip (1.7MB)
Collecting decorator>=4.3.0 (from networkx==2.2)
  Downloading https://files.pythonhosted.org/packages/71/bd/042e63027bea950da4e6f5545eb59b973868da854ab30a18128d3b884104/decorator-5.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-frcDUw/decorator/setup.py", line 4, in <module>
        exec(open('src/decorator.py').read(), dic)  # extract the __version__
      File "<string>", line 162
        print('Error in generated code:', file=sys.stderr)
                                              ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-frcDUw/decorator/
The command '/bin/bash -o pipefail -c pip install simple-pid pygame networkx==2.2' returned a non-zero code: 1

Please help me fix this issue.

**Comment by Alvin-LiuGuangyuan** [comment]
hi please try replace the Docker file step 14 with pip install simple-pid pygame decorator==4.4.2
