### ISSUE TITLE
Autoware warnings -- "base_link" passed to lookupTransform argument target_frame does not exist. Necessary topics are not subscribed yet ... 

### ISSUE THREAD

**Issue by mattdst1** [carla-simulator/carla-autoware#131]
I'm running Carla 0.9.10.1 using Carla Autoware. Previously ran and installed this image without issues. Running fresh install of Ubuntu 18.04 lts. Verified that autoware-contents all installed correctly. 

Can't figure out how to debug this issue and really need some help on this one. 

I'm getting the issues shown below in the terminal:
- [ WARN] [1625137899.394870991]: Necessary topics are not subscribed yet ... 
- [ WARN] [1625137899.424981928, 857.794570136]: Necessary topics are not subscribed yet. Waiting...
- [ WARN] [1625137898.387848978, 856.744570121]: "base_link" passed to lookupTransform argument target_frame does not exist. 
- [ERROR] [1625137898.387909340, 856.744570121]: Failed transform from base_link to ego_vehicle/lidar/lidar1

Then either:

- [ INFO] [1625138423.244008353, 6124.144648611]: [range_vision_fusion] Empty Detections. Make sure the vision and range detectors are running.

Or:

[roi_object_filter] Empty input messages, for details check the topics : /grid_map_wayarea and /detection/lidar_detector/objects.

![screenshot](https://user-images.githubusercontent.com/35136444/124120159-53f73d80-da6b-11eb-904e-f8e39fad5236.png)
![files](https://user-images.githubusercontent.com/35136444/124120163-578ac480-da6b-11eb-8f59-94280d2bae99.png)

**Comment by AOOOOOA** [comment]
> I'm running Carla 0.9.10.1 using Carla Autoware. Previously ran and installed this image without issues. Running fresh install of Ubuntu 18.04 lts. Verified that autoware-contents all installed correctly.
> 
> Can't figure out how to debug this issue and really need some help on this one.
> 
> I'm getting the issues shown below in the terminal:
> 
> * [ WARN] [1625137899.394870991]: Necessary topics are not subscribed yet ...
> * [ WARN] [1625137899.424981928, 857.794570136]: Necessary topics are not subscribed yet. Waiting...
> * [ WARN] [1625137898.387848978, 856.744570121]: "base_link" passed to lookupTransform argument target_frame does not exist.
> * [ERROR] [1625137898.387909340, 856.744570121]: Failed transform from base_link to ego_vehicle/lidar/lidar1
> 
> Then either:
> 
> * [ INFO] [1625138423.244008353, 6124.144648611]: [range_vision_fusion] Empty Detections. Make sure the vision and range detectors are running.
> 
> Or:
> 
> [roi_object_filter] Empty input messages, for details check the topics : /grid_map_wayarea and /detection/lidar_detector/objects.
> 
> ![screenshot](https://user-images.githubusercontent.com/35136444/124120159-53f73d80-da6b-11eb-904e-f8e39fad5236.png) ![files](https://user-images.githubusercontent.com/35136444/124120163-578ac480-da6b-11eb-8f59-94280d2bae99.png)

Hi, I also met this problem. How do you solve it?  thanks
Or could you please help with that? Thanks! @joel-mb @fpasch @johannesquast

**Comment by mattdst1** [comment]
Nope sorry, ended up leaving the PhD looking at this.
