### ISSUE TITLE
No GNSS information

### ISSUE THREAD

**Issue by hpliu1** [carla-simulator/carla-autoware#21]
When I used the carla_autoware_bridge_with_manual_control.launch for other towns, the GNSS in pygame window always showed zeros for the car location. 

Does it have the GNSS information for carla autoware bridge?

Thanks.

**Comment by fpasch** [comment]
That should (only) be a bug within the visualization.
The GNSS data is still published on topic ```/carla/ego_vehicle/gnss/front/gnss```
