### ISSUE TITLE
Failed to find match for field 'intensity'

### ISSUE THREAD

**Issue by wzhang1** [carla-simulator/carla-autoware#22]
It seems that Carla 0.9.4 only generate 3D points without intensity, is there any plan to have point could points in the form of  [x, y, z, intensity]?  In real world application, e.g. localization, intensity is quite an important field, thank you!

**Comment by fpasch** [comment]
The carla-autoware-bridge is only the consumer of the data.
Could you please open an issue within [carla ](https://github.com/carla-simulator/carla/issues/new) itself?
