### ISSUE TITLE
CARLA challenge instructions 

### ISSUE THREAD

**Issue by hatem-darweesh** [carla-simulator/carla-autoware#33]
Hello, 
I am looking for simple guide to use Autoware in  the Challenge. 
My problems are: 
- Sequence of running each of (simulator, scenario runner, evaluator , autoware stack) 
- when I use point cloud based localization, it is very slow. 
- can I use position published by the bridge instead of autoware localization ? 

Thanks.

**Comment by fpasch** [comment]
Details can now be found here:
https://github.com/carla-simulator/carla-autoware/tree/master/docker/challenge

**Comment by saurabhjha1** [comment]
I cannot locate this file. Is there a tutorial on how  to use Carla challenge scenarios with Autoware? Thanks!
