### ISSUE TITLE
error when run the command    $git submodule update --init

### ISSUE THREAD

**Issue by sheepwxy** [carla-simulator/carla-autoware#40]
Hello, I am trying to connect  the Autoware and carla, but when I use the command"git submodule update --init ", It shows the error as below, anyone can help?

> fatal: reference is not a tree: 33bd00b6441875c4d086f9f6f33ad915ae44e1b1
Unable to checkout '33bd00b6441875c4d086f9f6f33ad915ae44e1b1' in submodule path 'docker/challenge/scenario_runner'

**Comment by fpasch** [comment]
resolved by #45
