### ISSUE TITLE
ImportError: No module named ackermann_msgs.msg

### ISSUE THREAD

**Issue by jan-reich** [carla-simulator/carla-autoware#5]
I built the carla-autoware-bridge as described in the install notes. 
When executing 
`roslaunch carla_autoware_bridge carla_autoware_bridge.launch`
the vehiclecmd_to_ackermanndrive node is dying with the following error message:
`Traceback (most recent call last):
  File "/home/reich/carla-autoware/catkin_ws/src/carla_autoware_bridge/src/vehiclecmd_to_ackermanndrive", line 4, in <module>
    from ackermann_msgs.msg import AckermannDrive
ImportError: No module named ackermann_msgs.msg
[vehiclecmd_to_ackermanndrive-6] process has died [pid 30370, exit code 1, cmd /home/reich/carla-autoware/catkin_ws/src/carla_autoware_bridge/src/vehiclecmd_to_ackermanndrive __name:=vehiclecmd_to_ackermanndrive __log:=/home/reich/.ros/log/ed39ca24-2679-11e9-8cb1-485b3976f12a/vehiclecmd_to_ackermanndrive-6.log].
log file: /home/reich/.ros/log/ed39ca24-2679-11e9-8cb1-485b3976f12a/vehiclecmd_to_ackermanndrive-6*.log`

As the normal ros-bridge is already dependent on the AckermannDrive message, I wonder, where this message is defined as I didn't find any .msg file for it.

Could someone help me in this regard?

**Comment by fpasch** [comment]
Please make sure, that you have installed ros-kinetic-​ackermann-msgs.

**Comment by jan-reich** [comment]
Thank you very much :-)

**Comment by mrgransky** [comment]
`sudo apt-get update`
`sudo apt-get install ros-kinetic-​ackermann-msgs`
should fix the issue!

**Comment by leaves369** [comment]
ros2-humble has installed ackermann-msgs but has  <error: ‘ackermann_msgs’ was not declared in this scope> when build
