### ISSUE TITLE
range_fusion will be removed.

### ISSUE THREAD

**Issue by hakuturu583** [carla-simulator/carla-autoware#7]
In Autoware, range_fusion package will be removed in the future.(https://github.com/CPFL/Autoware/pull/1884)

**Comment by hakuturu583** [comment]
vision_klt_track also will be removed in the future.(https://github.com/CPFL/Autoware/pull/1875)

**Comment by icolwell** [comment]
FYI the launch files located at `Autoware/docs/quick_start` still reference these deleted packages.
Do these launch files get reviewed at each release? or would it be helpful if I created a PR on the develop branch to update them?
