### ISSUE TITLE
How to convert towns provided with CARLA to PointCloud Maps?

### ISSUE THREAD

**Issue by wangludong** [carla-simulator/carla-autoware#82]
Hi guys!
I've created my own map and ran it successfully in Carla, now I'd like to run it in Autoware.
So does anyone know how to convert it like the ones provided with this repo?

**Comment by fpasch** [comment]
What do you want to achieve?
If you want the Autoware localization, you might need to [create a point clloud of your map](https://github.com/carla-simulator/ros-bridge/tree/master/pcl_recorder).
Please also ensure, that routes can be calculated (waypoints are available).
