### ISSUE TITLE
RLException while trying to launch devel.

### ISSUE THREAD

**Issue by timoderbeste** [carla-simulator/carla-autoware#83]
Hi, 

When I am trying to run the code below, 

```
export CARLA_AUTOWARE_ROOT=~/carla-autoware/autoware_launch
export CARLA_MAPS_PATH=~/carla-autoware/autoware_data/maps
source $CARLA_AUTOWARE_ROOT/../catkin_ws/devel/setup.bash
export PYTHONPATH=$PYTHONPATH:~/carla-python/carla/dist/carla-<carla-version>-py2.7-linux-x86_64.egg:~/carla-python/carla/
roslaunch $CARLA_AUTOWARE_ROOT/devel.launch
```

I got some weird error that no one seems to have had:
```
... logging to /home/ubuntu/.ros/log/67f78d5c-7578-11ea-a5d1-0a2a123dc1e4/roslaunch-ip-172-31-32-244-11127.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

RLException: unused args [sensor_height] for include of [/home/ubuntu/autoware.ai/install/points_preprocessor/share/points_preprocessor/launch/ray_ground_filter.launch]
The traceback for the exception was written to the log file
```

I followed the exact same steps as described in the readme. I run an instance of carla in a docker container. I built autoware from source. 

The only thing that may be tricky can be that I am running on a EC2 instance on AWS. However, I doubt this is likely the issue. 

Thanks for any suggestions!

**Comment by joel-mb** [comment]
Hi @timoderbeste 
Please, try with the new instructions as the repo has been largely updated. Feel free to re-open the issue if the problem persists.
