### ISSUE TITLE
Is there a vector map in Carla?

### ISSUE THREAD

**Issue by JackRen88** [carla-simulator/carla-autoware#89]
Hello,I notice that a vector map is loaded in rviz which runs the open planner? I wander that currently if a vector map is  provided in carla town.

**Comment by joel-mb** [comment]
Hi @JackRen88!
Currently, we are providing vector maps for Town01 and Town02 (You can find them here: https://bitbucket.org/carla-simulator/autoware-contents/src/master/maps/vector_maps/). We are currently working to integrate the traffic lights and to provide the rest of the Towns.
